@startuml
title Поток работы: Пассажир
skinparam defaultFontName "Arial"
start
:Вход в систему;

if (Есть аккаунт?) then (да)
  :Введите данные (логин/пароль);
  while (Верные данные?) is (нет)
    :Повторить ввод;
  endwhile (да)
else (нет)
  :Зарегистрируйтесь;
  :Считывание логина и пароля;
endif

:Войти в систему;
:Выберите тариф и маршрут;
:Выберите способ оплаты;
:Оформление заказа,\nназначение водителя, оплата;

if (Хотите отменить поездку?) then (да)
  :Отмена поездки, возврат денег;
endif

if (Возникли проблемы?) then (да)
  :Обратитесь в поддержку;
  :Создание тикета, решение ситуации;
endif

:Оставьте отзыв водителю;
if (Оставил отзыв?) then (да)
  :Считать отзыв;
else (нет)
  :Ничего не делать;
endif
stop
@enduml